### ISSUE TITLE
LICENSE?

### ISSUE THREAD

**Issue by bogovicj** [image-transform-converters/image-transform-converters#1]

**Comment by bogovicj** [comment]
[BSD-2](https://opensource.org/licenses/BSD-2-Clause) okay with you? (its what imglib2 uses)
@NicoKiaru @tischi

**Comment by tischi** [comment]
Sure (frankly I don't know much about it..)

**Comment by bogovicj** [comment]
We'll stick with BSD-2 then

**Comment by NicoKiaru** [comment]
> [BSD-2](https://opensource.org/licenses/BSD-2-Clause) okay with you? (its what imglib2 uses)
> @NicoKiaru @tischi

I'm late! Not an expert, so that's ok for me !
