### ISSUE TITLE
Read Bdv AffineTransform

### ISSUE THREAD

**Issue by tischi** [image-transform-converters/image-transform-converters#12]
@NicoKiaru @bogovicj 
Do we have anything to read an `AffineTransform3D` from a `bdv.xml`?

**Comment by bogovicj** [comment]
Don't think so, but it's a good idea, I'll try to do this today

**Comment by tischi** [comment]
I started working on it...
https://github.com/image-transform-converters/image-transform-converters/blob/master/src/main/java/itc/transforms/bdv/BdvTransform.java#L16

**Comment by tischi** [comment]
> Don't think so, but it's a good idea, I'll try to do this today

I will do it today

**Comment by tischi** [comment]
I think I am done.
However, one question: the Bdv transform is from voxel units to physical units, right?

**Comment by bogovicj** [comment]
>  the Bdv transform is from voxel units to physical units, right?

Yes.
Well that's what it *should* be.

**Comment by tischi** [comment]
Ok! Thanks!
If you wish you could test my code:
https://github.com/image-transform-converters/image-transform-converters/blob/master/src/main/java/itc/transforms/bdv/BdvTransform.java#L16
But I'll close the issue for now.
