### ISSUE TITLE
ElastixAffineToAffineTransform3D

### ISSUE THREAD

**Issue by tischi** [image-transform-converters/image-transform-converters#16]
@NicoKiaru @bogovicj 
Did one of you guys maybe already write some code for this, somewhere? :-)

https://github.com/image-transform-converters/image-transform-converters/blob/master/src/main/java/itc/converters/ElastixAffineToAffineTransform3D.java#L35

**Comment by NicoKiaru** [comment]
Yes in the scijava-converters branch... I can merge it (but it s not tested)

**Comment by tischi** [comment]
Sorry, I saw this too late. I pushed mine already. Seems to work...

**Comment by NicoKiaru** [comment]
Let's close this, then ?
