### ISSUE TITLE
Transform Interval

### ISSUE THREAD

**Issue by tischi** [image-transform-converters/image-transform-converters#17]
Hi @bogovicj @NicoKiaru,

Not sure who added this, maybe was myself, but I think it this and the function below does not make sense:

- https://github.com/image-transform-converters/image-transform-converters/blob/master/src/main/java/itc/utilities/TransformUtils.java#L19

If the transformation contains a rotation the transformed corners of the interval are quite useless or even misleading. What do you think? Shall we remove this?
This only makes sense for scaling transforms, but then we should restrict it to this, no?

**Comment by bogovicj** [comment]
It was me.  Pretty sure I have a more general version - I say let's remove it now, and if track down something correct, I'll add it back in (probably PR so you can have a look first).  

Sound good?

**Comment by tischi** [comment]
Cool!

**Comment by NicoKiaru** [comment]
@tischi @bogovicj this issue is written as invalid. Can I close it ?

**Comment by bogovicj** [comment]
okay by me to close this.
