### ISSUE TITLE
Maven error: invalid name

### ISSUE THREAD

**Issue by tischi** [image-transform-converters/image-transform-converters#18]
@bogovicj @NicoKiaru 
I just pushed some additions and now I cannot `mvn clean install` it anymore, but am getting this error:
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jar-plugin:3.1.2:jar (default-jar) on project image-transform-converters: Error assembling JAR: Invalid automatic module name: '' -> [Help 1]
```
Could you please pull and see what is wrong? I don't get it....

**Comment by NicoKiaru** [comment]
You need to name the package explicitely. I don t know where it is, but you should find somewhere on gitter or on the forum.

**Comment by tischi** [comment]
https://forum.image.sc/t/pom-scijava-27-0-1-causes-error-assembling-jar-during-build/27167
