### ISSUE TITLE
ElastixSimilarity converter takes a ElastixEuler input argument

### ISSUE THREAD

**Issue by NicoKiaru** [image-transform-converters/image-transform-converters#31]
I guess this is a mistake and not yet implement ?

https://github.com/image-transform-converters/image-transform-converters/blob/9910e9fcba7db19c935d0bc7cfb4d6723fbb03c6/src/main/java/itc/converters/ElastixSimilarity3DToAffineTransform3D.java#L62

@tischi

**Comment by tischi** [comment]
Right, this seems to be a WIP with a wrong name.
Maybe we just delete it?

**Comment by NicoKiaru** [comment]
Oki, doc, I'll try to implement it - I may need the 2d version

**Comment by NicoKiaru** [comment]
I'll close this issue and open new ones for the missing converters
